FROM python:3.11-slim
WORKDIR /workspace
ENV PYTHONUNBUFFERED=1
RUN pip install --no-cache-dir -i https://pypi.tuna.tsinghua.edu.cn/simple jupyterlab
EXPOSE 8888
CMD ["jupyter","lab","--ip=0.0.0.0","--port=8888","--no-browser","--allow-root","--NotebookApp.token=''"]
